# Generated by Django 6.0.4 on 2026-04-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crise',
            name='instituicao',
        ),
        migrations.RenameField(
            model_name='crise',
            old_name='descricao_completa',
            new_name='descricao_bruta',
        ),
        migrations.RemoveField(
            model_name='crise',
            name='necessidades_urgentes',
        ),
        migrations.AddField(
            model_name='crise',
            name='analise_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('VOLUNTARIO', 'Voluntário'), ('ONG', 'Instituição')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='habilidades',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
